plugins {
    id 'application'
}

dependencies {
    implementation project(':lostrego')
    implementation project(':lostrego-spy-common')
    implementation libs.picocli
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

application {
    mainClass = 'com.angazo.lostrego.spy.Main'
    mainModule = 'com.angazo.lostrego.spy'
    applicationDefaultJvmArgs = ['--enable-native-access=com.angazo.lostrego']
}
